# fly.toml app configuration file generated for nikocale on 2024-09-07T17:28:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nikocale'
primary_region = 'nrt'
console_command = "php /var/www/html/laravel/artisan tinker"

[build]
  dockerfile = "Dockerfile.prod"
  release_command = "php /var/www/html/laravel/artisan migrate --force"

[deploy]
  release_command = "php artisan migrate --force"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
